# A similar terminal is kitty. See this slightly salty issue on kitty, lol
# https://github.com/kovidgoyal/kitty/issues/2701


selection:
  save_to_clipboard: true

mouse_bindings:
- { mouse: Middle, action: PasteSelection }

window:
  # Values for `decorations`:
  # - full: Borders and title bar
  # - none: Neither borders nor title bar
  # 
  # Values for `decorations` (macOS only):
  # - transparent: Title bar, transparent background and title bar buttons
  # - buttonless: Title bar, transparent background and no title bar buttons
  decorations: none

# TODO: colors?

# by default on Mac OS option+letter will produce special characters: ˙∆˚¬
# setting this to true makes it produce the escape code then the letter, which
# is how option has been implemented since the whole ASCII thing shook out.
#
# True meta is not supported by alacritty.
#alt_send_esc: true
