#!/bin/bash

# Install vundle plugin for vimrc
if [ ! -d ~/.vim/bundle/vundle ]; then
   mkdir -p ~/.vim/bundle/vundle
   git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

# Install git-bash-prompt
if [ ! -d ~/.bash-git-prompt ]; then
   git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt
fi

# Install tmux plugin manager
if [ ! -d ~/.tmux/plugins/tpm ]; then
   git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
   ~/.tmux/plugins/tpm/bin/install_plugins
fi

# Configure vim
ln -sf `pwd`/.vimrc ~
mkdir -p ~/.vim/backupdir
mkdir -p ~/.vim/undodir
mkdir -p ~/.vim/swpdir
vim +BundleInstall! +qall

# Configure screen
ln -sf `pwd`/.screenrc ~

# Configure tmux
ln -sf `pwd`/.tmux.conf ~

# Configure mercurial
#ln -sf `pwd`/mercurial/.hgrc ~
#ln -sf `pwd`/mercurial/hgignore.ini ~/.hgignore

# If cygwin, configure mintty
if [[ `uname` == *"CYGWIN"* ]]; then
   echo "Installing cygwin specific files"
   ln -sf `pwd`/.minttyrc ~
fi

# Configure git
git config --global include.path `pwd`/gitconfig
if [ -z `git config --global user.email` ]; then
   echo "REMEMBER: Tell git your email like this: git config --global user.email \"philipjagielski@gmail.com\""
fi

# source .bashrc_dotfiles if .bashrc doesn't already
if [ ! -a ~/.bashrc ]; then
   touch ~/.bashrc
fi
if ! grep -q bashrc_dotfiles ~/.bashrc; then
   echo "Sourcing bashrc_dotfiles in .bashrc"
   echo "source `pwd`/.bashrc_dotfiles" >> ~/.bashrc
   . ~/.bashrc
fi
