#!/bin/bash

# Install vim
if [ -a ~/.vimrc ]; then
  mv ~/.vimrc ~/.vimrc.bak
fi
ln -sf `pwd`/vim/.vimrc ~
vim +BundleInstall! +qall

# Install tmux
if [ -a ~/.tmux.conf ]; then
  mv ~/.tmux.conf ~/.tmux.conf.bak
fi
ln -sf `pwd`/.tmux.conf ~
